In [4]:
import yfinance as yf
import datetime 
from datetime import date, timedelta

start_date = datetime.datetime(2015, 1, 1)
end_date  = datetime.datetime(2023, 8, 23)



my_stocks = yf.download(tickers = ["GOOGL", "PANW", "AMZN", "BUD", "AAPL", "MSFT", "GME", "TSLA", "NFLX", "META", "WMT", "WBA", "NVDA"]
, start=start_date, end=end_date, group_by='tickers')
my_stocks.head(13)

[*********************100%%**********************]  13 of 13 completed

                   BUD                                                 \
                  Open        High         Low       Close  Adj Close
Date
2015-01-02  112.300003  112.480003  110.980003  111.739998  91.221924
2015-01-05  109.040001  109.709999  107.769997  108.089996  88.242157
2015-01-06  107.279999  108.540001  106.570000  107.849998  88.046219
2015-01-07  108.440002  109.949997  108.139999  109.419998  89.327934
2015-01-08  111.589996  113.769997  111.379997  112.879997  92.152603
2015-01-09  113.290001  113.440002  111.489998  111.970001  91.409721
2015-01-12  113.629997  113.849998  112.449997  113.459999  92.626114
2015-01-13  114.930000  115.430000  113.190002  113.889999  92.977142
2015-01-14  113.779999  114.370003  112.660004  113.529999  92.683243
2015-01-15  114.419998  115.040001  113.750000  114.239998  93.262878
2015-01-16  115.989998  117.089996  114.839996  117.010002  95.524231
2015-01-20  118.230003  118.250000  115.750000  116.739998  95.303802
2015-01-21  117.519997  118.570000  116.739998  117.750000  96.128357

                          NFLX                                   ...  \
             Volume       Open       High        Low      Close  ...
Date                                                             ...
2015-01-02   908400  49.151428  50.331429  48.731430  49.848572  ...
2015-01-05  2010600  49.258572  49.258572  47.147144  47.311428  ...
2015-01-06  1717700  47.347141  47.639999  45.661430  46.501431  ...
2015-01-07  1837000  47.347141  47.421429  46.271427  46.742859  ...
2015-01-08  1257200  47.119999  47.835712  46.478573  47.779999  ...
2015-01-09   968900  47.631428  48.020000  46.898571  47.041428  ...
2015-01-12  1176800  47.090000  47.198570  45.264286  45.547142  ...
2015-01-13  3495600  46.021427  47.048573  45.900002  46.255714  ...
2015-01-14   892800  47.071430  47.369999  45.680000  46.320000  ...
2015-01-15  1218000  46.547142  46.785713  45.844288  46.251431  ...
2015-01-16  1504400  46.857143  48.250000  46.381428  48.191429  ...
2015-01-20  1195300  48.571430  50.000000  47.714287  49.828571  ...
2015-01-21  1705800  59.234287  59.240002  57.410000  58.468571  ...

                 PANW                                       WBA             \
                  Low      Close  Adj Close   Volume       Open       High
Date
2015-01-02  39.200001  40.473331  40.473331  4951200  76.110001  77.190002
2015-01-05  40.060001  41.243332  41.243332  4050600  75.080002  75.900002
2015-01-06  39.363335  40.616669  40.616669  4053600  75.970001  76.000000
2015-01-07  41.209999  41.843334  41.843334  3791400  75.050003  76.690002
2015-01-08  41.933334  42.403332  42.403332  2144400  77.300003  77.940002
2015-01-09  41.926666  41.939999  41.939999  2781600  77.309998  77.540001
2015-01-12  41.333332  42.426666  42.426666  2626500  75.800003  76.190002
2015-01-13  41.060001  41.583332  41.583332  3415200  75.199997  76.290001
2015-01-14  41.066666  42.099998  42.099998  2451300  74.940002  75.419998
2015-01-15  40.433334  40.693333  40.693333  3483900  75.919998  76.099998
2015-01-16  40.526669  41.669998  41.669998  2538000  74.470001  76.120003
2015-01-20  40.753334  41.486668  41.486668  2329200  76.080002  76.489998
2015-01-21  41.020000  41.783333  41.783333  2274900  75.519997  76.449997


                  Low      Close  Adj Close   Volume
Date
2015-01-02  75.089996  76.000000  57.365662  3938500
2015-01-05  74.269997  74.500000  56.233452  4767900
2015-01-06  73.940002  74.690002  56.376854  4881600
2015-01-07  74.959999  76.599998  57.818542  5672100
2015-01-08  76.860001  77.550003  58.535625  4083900
2015-01-09  75.610001  75.669998  57.116573  3704100
2015-01-12  74.839996  75.699997  57.139210  2910700
2015-01-13  74.110001  75.260002  56.807106  5173200
2015-01-14  74.260002  74.989998  56.603298  3263200
2015-01-15  74.610001  74.779999  56.444786  3574500
2015-01-16  74.400002  76.029999  57.388309  4881900
2015-01-20  75.309998  76.050003  57.403416  2744500
2015-01-21  75.059998  75.589996  57.056190  2549400

[13 rows x 78 columns]